name: sitename
recipe: wordpress
proxy:
  # nginx: # Optional: if you exclude this, Lando will serve it as bedrock.lndo.site
  #   - sitename.test
  node: # webpack-dev-server url
    - localhost:8080
config:
  php: "7.3"
  via: nginx
  webroot: web
  database: mariadb
  xdebug: true

# More containers such as build processes or CI flows
services:
  node:
    type: node
    services:
      ports:
        - 8080:8080

# Example usage: run `lando npm run build` or `lando yarn run build`
tooling:
  npm:
    service: node
  yarn:
    service: node
